steps:
  # Pull to use as cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/$_PROJECT_NAME:latest || exit 0']

  # Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t', 'gcr.io/${PROJECT_ID}/$_PROJECT_NAME:latest', 
            '-t', '$_PROJECT_NAME:latest', 
            '--cache-from', 'gcr.io/$PROJECT_ID/$_PROJECT_NAME:latest',
            '.']

  # Run tests
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'run',
            '$_PROJECT_NAME:latest', 
            'python -m unittest discover']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/$PROJECT_ID/$_PROJECT_NAME:latest']

  ## Scan image - we can scan our image
  ## or have automatic scanning, refer to:
  ## https://cloud.google.com/container-analysis/docs/automated-scanning-howto
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'gcloud'
  #   args: ['artifacts', 'docker', 'images', 'scan',
  #          'gcr.io/${PROJECT_ID}/$_PROJECT_NAME:latest']
  
  # Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', '$_PROJECT_NAME',
           '--image=gcr.io/${PROJECT_ID}/$_PROJECT_NAME:latest',
           '--region=us-central1']
substitutions:
  _PROJECT_NAME: 'rickandmorty-api'
## we can use higher cpu machines
# options:
#   machineType: 'N1_HIGHCPU_8'