apiVersion: v1
kind: Service
metadata:
  name: {{ include "rickandmorty.fullname" . }}
  labels:
    {{- include "rickandmorty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: rickandmorty
  selector:
    {{- include "rickandmorty.selectorLabels" . | nindent 4 }}
