name: Test rickandmorty

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.0
        with:
          minikube version: 'v1.16.0'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: enable nginx ingress controller
        run: |
          minikube config set vm-driver docker
          minikube delete
          minikube start
          minikube addons enable ingress
          minikube addons list
      - name: build image, install chart
        run: |
          cd /home/runner/work/rickandmorty/rickandmorty
          eval $(minikube docker-env) && docker build . -t rickandmorty
          helm install rickandmorty ./helm/rickandmorty
      - name: test service
        run: |
          sudo -- sh -c "echo \"$(minikube ip) rickandmorty.example\" >> /etc/hosts"
          cat /etc/hosts
          echo "wait 30sec for it to start..."
          sleep 30
          curl --fail rickandmorty.example/healthcheck
          curl --fail rickandmorty.example/chars/sp/Human/st/Alive/o/Earth
          # TODO: test the main endpoint using curl and jq
